/**
 * Generates RESULTS.md: a deterministic overview of every benchmark run found
 * in the result folders. Read-only with respect to result folders.
 *
 *   npx tsx scripts/scoreboard.ts          # write RESULTS.md
 *   npx tsx scripts/scoreboard.ts --check  # fail if RESULTS.md is stale
 */
import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const RESULT_DIR = /_\d{4}-\d{2}-\d{2}(_.*)?$/;
const DURATION = /^duration-(\d+)-seconds\.txt$/;

interface Run {
  readonly label: string;
  readonly durationSeconds: number | null;
  readonly files: readonly string[];
}

function listDirs(path: string): string[] {
  try {
    return readdirSync(path).filter((n) => statSync(resolve(path, n)).isDirectory());
  } catch {
    return [];
  }
}

function readRun(challengeDir: string, label: string): Run {
  const dir = resolve(challengeDir, label);
  const entries = readdirSync(dir);
  let durationSeconds: number | null = null;
  const files: string[] = [];
  for (const entry of entries) {
    const m = DURATION.exec(entry);
    if (m) {
      durationSeconds = Number(m[1]);
      continue;
    }
    if (entry === "duration.txt") continue;
    files.push(entry);
  }
  files.sort();
  return { label, durationSeconds, files };
}

const challenges = listDirs(root)
  .filter((n) => /^challenge\d+/.test(n))
  .sort();

const lines: string[] = [
  "# Benchmark results",
  "",
  "Auto-generated by `scripts/scoreboard.ts` — do not edit by hand. Each row is",
  "one run (a `[harness]_[model]_[quant]_[date]` result folder); the duration is",
  "from its `duration-<secs>-seconds.txt` marker.",
  "",
];

for (const challenge of challenges) {
  const challengeDir = resolve(root, challenge);
  const runs = listDirs(challengeDir)
    .filter((n) => RESULT_DIR.test(n) && n !== "grader")
    .sort()
    .map((label) => readRun(challengeDir, label));

  lines.push(`## ${challenge}`, "");
  if (runs.length === 0) {
    lines.push("_No runs yet._", "");
    continue;
  }
  lines.push("| Run | Duration | Deliverables |", "| --- | --- | --- |");
  for (const run of runs) {
    const dur = run.durationSeconds === null ? "—" : `${run.durationSeconds}s`;
    lines.push(`| \`${run.label}\` | ${dur} | ${run.files.join(", ") || "—"} |`);
  }
  lines.push("");
}

const content = lines.join("\n");
const target = resolve(root, "RESULTS.md");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    /* missing */
  }
  if (current !== content) {
    console.error("RESULTS.md is stale. Run: npx tsx scripts/scoreboard.ts");
    process.exit(1);
  }
  console.log("RESULTS.md is up to date.");
} else {
  writeFileSync(target, content);
  console.log(`Wrote ${target}`);
}
